### ISSUE TITLE
Use git path for cyclejs dependency

### ISSUE THREAD

**Issue by ivan-kleshnin** [danyx23/cyclejsBMI#2]
> This branch is built against the stream branch of cycle, and as such you can't use npm currently to build it but need to check out the stream branch of cycle into a directory next to the cyclejsBMI directory (relative path is hardcoded in index.html)

Solution:

``` javascript
// package.json
"dependencies": {
  "cyclejs": "git://github.com/staltz/cycle.git#streams",
}
```

**Comment by danyx23** [comment]
Oh ... of course! Thank you!

**Comment by ivan-kleshnin** [comment]
It's worth adding that unfortunately `#stream` branch of CycleJS does not include `/lib` folder.
You need to also build it on yourself:

```
$ cd node_modules/cyclejs
$ npm run compile-lib
```

**Comment by danyx23** [comment]
Yes I just realized this - but anyhow, this is much nicer than my previous solution, thank you! Just published an update with your suggested fix.
